"""Sincronizando migraciones

Revision ID: 3979a191b4dd
Revises: b4a4d00a97a2
Create Date: 2025-03-15 21:58:53.377283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3979a191b4dd'
down_revision = 'b4a4d00a97a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Solicitudes_Afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('zona', sa.Enum('Rural', 'Urbana'), nullable=False),
    sa.Column('sexo', sa.Enum('Femenino', 'Masculino'), nullable=False),
    sa.Column('ficha_sisben', sa.Enum('Grupo A', 'Grupo B', 'Grupo C', name='sisben_groups'), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Aprobado', 'Rechazado'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Confirmada', 'Cancelada', 'Atendida'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('farmacia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmacia_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_notificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receta_medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subadministrador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('indicaciones', sa.Text(), nullable=False),
    sa.Column('fecha_prescripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['subadministrador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notificaciones')
    op.drop_table('recetas_medicas')
    op.drop_table('medicamentos')
    op.drop_table('citas')
    with op.batch_alter_table('solicitudes_afiliacion', schema=None) as batch_op:
        batch_op.drop_index('numero_documento')

    op.drop_table('solicitudes_afiliacion')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('primer_nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('segundo_nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('primer_apellido',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('segundo_apellido',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('departamento',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('zona',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('estado')
        batch_op.drop_column('contraseña')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('primer_nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('primer_apellido',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('usuario',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.create_unique_constraint(None, ['usuario'])
        batch_op.create_unique_constraint(None, ['numero_documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('usuario',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('primer_apellido',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('primer_nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('estado', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True))
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('zona',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('departamento',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('segundo_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('primer_apellido',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('segundo_nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('primer_nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    op.create_table('solicitudes_afiliacion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('primer_nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('primer_apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_apellido', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_documento', mysql.ENUM('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('zona', mysql.ENUM('Rural', 'Urbana'), nullable=False),
    sa.Column('sexo', mysql.ENUM('Femenino', 'Masculino'), nullable=False),
    sa.Column('ficha_sisben', mysql.ENUM('Grupo A', 'Grupo B', 'Grupo C'), nullable=True),
    sa.Column('estado', mysql.ENUM('Pendiente', 'Aprobado', 'Rechazado'), server_default=sa.text("'Pendiente'"), nullable=True),
    sa.Column('fecha_solicitud', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_solicitudes_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('solicitudes_afiliacion', schema=None) as batch_op:
        batch_op.create_index('numero_documento', ['numero_documento'], unique=True)

    op.create_table('citas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.Column('motivo', mysql.TEXT(), nullable=False),
    sa.Column('estado', mysql.ENUM('Pendiente', 'Confirmada', 'Cancelada', 'Atendida'), server_default=sa.text("'Pendiente'"), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], name='citas_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('medicamentos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=False),
    sa.Column('imagen_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('farmacia_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['farmacia_id'], ['usuario.id'], name='fk_medicamentos_farmacia', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('recetas_medicas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subadministrador_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('medicamento_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('indicaciones', mysql.TEXT(), nullable=False),
    sa.Column('fecha_prescripcion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], name='recetas_medicas_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], name='recetas_medicas_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subadministrador_id'], ['usuario.id'], name='recetas_medicas_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('notificaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mensaje', mysql.TEXT(), nullable=False),
    sa.Column('leido', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_notificacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='notificaciones_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('receta_medica')
    op.drop_table('notificacion')
    op.drop_table('medicamento')
    op.drop_table('consulta')
    op.drop_table('cita')
    op.drop_table('Solicitudes_Afiliacion')
    # ### end Alembic commands ###
