"""Migración corregida

Revision ID: 7db647e0b8db
Revises: 
Create Date: 2025-06-17 12:55:40.456562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db647e0b8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('tipo_solicitud', sa.Enum('PQR', 'Autorización', 'otro'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('url_boton', sa.String(length=200), nullable=True),
    sa.Column('texto_boton', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('Administrador', 'Subadministrador', 'Farmacia', 'paciente'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('afiliado', sa.Boolean(), nullable=True),
    sa.Column('debe_cambiar_clave', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('Solicitudes_Afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_expedicion', sa.Date(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('zona', sa.Enum('Rural', 'Urbana'), nullable=False),
    sa.Column('sexo', sa.Enum('Femenino', 'Masculino'), nullable=False),
    sa.Column('ficha_sisben', sa.Enum('Grupo A', 'Grupo B', 'Grupo C', name='sisben_groups'), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Aprobado', 'Rechazado'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('Analgésico', 'Antibiótico', 'Antiinflamatorio', 'Otro', name='tipo_medicamento'), nullable=True),
    sa.Column('concentracion', sa.String(length=50), nullable=True),
    sa.Column('presentacion', sa.Enum('Tableta', 'Jarabe', 'Inyectable', 'Crema', 'Otro', name='presentacion_medicamento'), nullable=True),
    sa.Column('laboratorio', sa.String(length=100), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('Disponible', 'Agotado', 'Vencido', name='estado_medicamento'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('farmacia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmacia_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_notificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=100), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=100), nullable=True),
    sa.Column('primer_apellido', sa.String(length=100), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_expedicion', sa.Date(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('ficha_sisben', sa.String(length=50), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('imagen_usuario', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_examen', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=20), nullable=False),
    sa.Column('codigo_confirmacion', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Programada', 'Confirmada', 'Cancelada', 'Atendida'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=255), nullable=False),
    sa.Column('especialidad', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receta_medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subadministrador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('indicaciones', sa.Text(), nullable=False),
    sa.Column('fecha_prescripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['subadministrador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registroretiromedicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('indicacion', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_tratamiento_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atencion_cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('indicacion', sa.String(length=255), nullable=False),
    sa.Column('fecha_atencion', sa.Date(), nullable=False),
    sa.Column('cantidad_recetada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atencion_cita')
    op.drop_table('registroretiromedicamento')
    op.drop_table('receta_medica')
    op.drop_table('historial_cita')
    op.drop_table('cita')
    op.drop_table('pacientes')
    op.drop_table('notificacion')
    op.drop_table('medicamento')
    op.drop_table('consulta')
    op.drop_table('Solicitudes_Afiliacion')
    op.drop_table('usuario')
    op.drop_table('slide')
    op.drop_table('contacto')
    # ### end Alembic commands ###
