"""Descripción de los cambios

Revision ID: e83291cc1444
Revises: 3979a191b4dd
Create Date: 2025-03-15 22:20:26.018140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e83291cc1444'
down_revision = '3979a191b4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Solicitudes_Afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('zona', sa.Enum('Rural', 'Urbana'), nullable=False),
    sa.Column('sexo', sa.Enum('Femenino', 'Masculino'), nullable=False),
    sa.Column('ficha_sisben', sa.Enum('Grupo A', 'Grupo B', 'Grupo C', name='sisben_groups'), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Aprobado', 'Rechazado'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    with op.batch_alter_table('solicitudes_afiliacion', schema=None) as batch_op:
        batch_op.drop_index('numero_documento')

    op.drop_table('solicitudes_afiliacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_afiliacion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('primer_nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('primer_apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('segundo_apellido', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_documento', mysql.ENUM('CC', 'TI', 'CE', 'Pasaporte'), nullable=False),
    sa.Column('numero_documento', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('zona', mysql.ENUM('Rural', 'Urbana'), nullable=False),
    sa.Column('sexo', mysql.ENUM('Femenino', 'Masculino'), nullable=False),
    sa.Column('ficha_sisben', mysql.ENUM('Grupo A', 'Grupo B', 'Grupo C'), nullable=False),
    sa.Column('estado', mysql.ENUM('Pendiente', 'Aprobado', 'Rechazado'), nullable=True),
    sa.Column('fecha_solicitud', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='solicitudes_afiliacion_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('solicitudes_afiliacion', schema=None) as batch_op:
        batch_op.create_index('numero_documento', ['numero_documento'], unique=True)

    op.drop_table('Solicitudes_Afiliacion')
    # ### end Alembic commands ###
